version: "3.8"
services:
  database: 
    container_name: database
    image: postgres:10.4-alpine
    ports:
      - ${PG_PORT}:${PG_PORT}
    command: -p ${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env


   