version: "3.8"
services:
  backend:
    container_name: backend
    image: ktu-airlines/backend:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - ${APP_PORT}:${APP_PORT}
      - ${JWT_TOKEN}:${JWT_TOKEN}
      - ${SWAGGER_USER}:${SWAGGER_USER}
      - ${SWAGGER_PASSWORD}:${SWAGGER_PASSWORD}
    restart: always
    build: 
      context: backend
      target: build
    command: npm run start:dev
    volumes:
      - ./volumes/backend:/usr/app
      - ./volumes/backend:/usr/app/node_modules