version: "3.8"
services:
  backend:
    image: danyakladnitsky/ktu-airlines.backend:latest
    environment:
      - ${APP_PORT}:${APP_PORT}
      - ${JWT_TOKEN}:${JWT_TOKEN}
      - ${SWAGGER_USER}:${SWAGGER_USER}
      - ${SWAGGER_PASSWORD}:${SWAGGER_PASSWORD}
      - ${PG_PORT}:${PG_PORT}
      - ${PG_HOST}:${PG_HOST}
    restart: always
    env_file:
      - .env
    command: npm run start:prod
  
  frontend:
    image: danyakladnitsky/ktu-airlines.frontend:latest
    restart: always
  
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend