version: "3.8"
services:
  database: 
    container_name: database
    image: postgres:10.4-alpine
    ports:
      - ${PG_PORT}:${PG_PORT}
    command: -p ${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    platform: linux/x86_64
    image: danyakladnitsky/ktu-airlines.backend:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - ${APP_PORT}:${APP_PORT}
      - ${JWT_TOKEN}:${JWT_TOKEN}
      - ${SWAGGER_USER}:${SWAGGER_USER}
      - ${SWAGGER_PASSWORD}:${SWAGGER_PASSWORD}
      - ${PG_PORT}:${PG_PORT}
      - ${PG_HOST}:${PG_HOST}
    restart: always
    depends_on: 
      - database
    env_file:
      - .env
    command: npm run start:prod

  frontend:
    platform: linux/x86_64
    image: danyakladnitsky/ktu-airlines.frontend:latest
    ports:
      - 81:80
    restart: always