export const COLORS = {
  PRIMARY_BACKGROUND: '#9775FA',
  SECONDARY_BACKGROUND: '#FAFAFA',
  HOVER_BACKGROUND: '#F8F9FA',
  FOCUS_BACKGROUND: '#C0EB75',
  PRIMARY_TEXT: '#25262B',
  SECONDARY_TEXT: '#868E96',
  ACCENT_TEXT: '#ffffff',
  SECONDARY_BUTTON: '#25262B',
  DISABLED_BUTTON: '#868E96',
};