name: Build and publish images

on:
  push:
    branches: [main]

jobs:
  push:
    name: Build and publish images
    runs-on: ubuntu-latest
    env:
      frontend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/ktu-airlines.frontend
      backend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/ktu-airlines.backend
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push backend image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{env.backend_rep}}:latest
          cache-from: type=registry,ref=${{env.backend_rep}}:latest
          cache-to: type=inline
          platforms: linux/x86_64
      -
        name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.frontend_rep}}:latest
          cache-from: type=registry,ref=${{env.frontend_rep}}:latest
          cache-to: type=inline
          platforms: linux/x86_64

