name: Deploy to staging server

on:
  push:
    branches:
      - dev

jobs:
  init:
    runs-on: ktu-airlines
    name: Check changed files
    outputs:
      backend: ${{ steps.check_files.outputs.backend }}
      frontend: ${{ steps.check_files.outputs.frontend }}
      nginx: ${{ steps.check_files.outputs.nginx }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file; do
              echo $file
              if [[ $file == backend/* ]]; then
                echo "backend service will be rebuilt"
                echo "::set-output name=backend::true"
              elif [[ $file == frontend/* ]]; then
                echo "frontend service will be rebuilt"
                echo "::set-output name=frontend::true"
              elif [[ $file == nginx/* ]]; then
                echo "nginx will be rebuild"
                echo "::set-output name=nginx::true"
              else
                echo "file does not belong to any service"
              fi
            done < files.txt

  push-to-registry:
    name: Build and publish images to Docker Registry
    runs-on: ubuntu-latest
    env:
      backend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/ktu-airlines.backend
      frontend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/ktu-airlines.frontend
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push backend image
        uses: docker/build-push-action@v4
        if: needs.init.outputs.backend == 'true'
        with:
          context: backend
          push: true
          tags: ${{env.backend_rep}}:latest
          cache-from: type=registry,ref=${{env.backend_rep}}:latest
          cache-to: type=inline
          platforms: linux/x86_64
      -
        name: Push frontend image
        uses: docker/build-push-action@v4
        if: needs.init.outputs.frontend == 'true'
        with:
          context: frontend
          push: true
          tags: ${{env.frontend_rep}}:latest
          cache-from: type=registry,ref=${{env.frontend_rep}}:latest
          cache-to: type=inline
          platforms: linux/x86_64

  pull-images:
    name: Pull and run images
    runs-on: ktu-airlines
    needs: push-images
    env:
      frontend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/ktu-airlines.frontend
      backend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/ktu-airlines.backend
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
  build-app:
    name: Build and publish services
    environment: DEV
    runs-on: ktu-airlines
    needs: pull-images
    steps:
      -
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PG_PORT: ${{ secrets.PG_PORT }}
          envkey_PG_USER: ${{ secrets.PG_USER }}
          envkey_PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          envkey_PG_DB: ${{ secrets.PG_DB }}
          envkey_PG_HOST: ${{ secrets.PG_HOST }}
          envkey_APP_PORT: ${{ secrets.APP_PORT }}
          envkey_JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          envkey_SWAGGER_USER: ${{ secrets.SWAGGER_USER }}
          envkey_SWAGGER_PASSWORD: ${{ secrets.SWAGGER_PASSWORD }}
          envkey_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          envkey_API_HOST: ${{ secrets.API_HOST }}
          envkey_BOT_CONFIRMATION: ${{ secrets.BOT_CONFIRMATION }}
          file_name: .env
          fail_on_empty: false
      -
        name: Copy env to frontend
        run: cp .env frontend/.env
      -
        name: Pull last images
        run: docker compose pull
      -
        name: Stop frontend
        run: docker compose --env-file .env down frontend 
        if: needs.init.outputs.frontend == 'true'
      -
        name: Stop backend
        run: docker compose --env-file .env down backend 
        if: needs.init.outputs.backend == 'true'
      -
        name: Stop nginx
        run: docker compose --env-file .env down nginx  
        if: needs.init.outputs.nginx == 'true'
      -
        name: Build services
        run: docker compose --env-file .env build
      -
        name: Run services
        run: docker compose --env-file .env up -d
      -
        name: Check services
        run: docker ps -a